name: Snake Animation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Masood0319
          outputs: dist/snake.svg

      - name: Push Snake to Repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update snake"
          branch: output
          create_branch: true
          file_pattern: dist/snake.svg
